name = "analytics_with_cloudflare"
main = "src/index.ts"
compatibility_date = "2024-06-14"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "waline-db"
database_id = "9137d1d8-7c46-4a39-b5f8-3fdb86022cc8"
